# Generated by Django 2.2.1 on 2019-05-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPointsTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transfer_dst', to='tournament.Group')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transfer_src', to='tournament.Group')),
            ],
        ),
    ]
