# Generated by Django 5.0.6 on 2024-05-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20190704_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTieRankingPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiepoints', models.PositiveSmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.group')),
                ('tph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.teamplaceholder')),
            ],
        ),
    ]
