version: "3"

services:

  tournament_scheduler:
    build: ./TournamentSchedulerDjango/
    container_name: TournamentSchedulerDjango
    ports:
      - ${DJANGO_PORT}:8844
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_DEBUG
      - DJANGO_PORT
    restart: unless-stopped
    volumes:
      - ../django:/srv/django
