MenElite:
  name: Men Elite
  teams:
    - RKV Berlin
    - KSV Glauchau
    - Kaniów BKT
    - Team Poznań
    - Set Kaniów
    - KVN Praha
    - VK Berlin
    - DRC Neuburg
    - WCH Berlin
    - KCNW U21
    - Alytus
    - POL U21
    - KP Bremen
    - KC Kelheim
    #- Katowice M
    #- KP Praha A

Ladies:
  name: Ladies
  teams:
    - Kaniów W
    - KCNW Berlin W
    - KSVH W
    - Neuburg W
    - Czech W
    - Hahaha Team W
    - Bremen W
    - Katowice W
    - Powiśle W

Men2:
  name: Men 2
  teams:
    - VMW Berlin Men
#    - Vidra Old Boys
    - Potsdam Men
    - Nagymaros Men
    - UKK Wien mix
    - Ukraine Men
    - Leśna Men
    - DobroPtaah

U18:
  name: U18
  teams:
    - Alytus U18
    - Czech U18 A
    - KCNW U16
    - Leśna U18
#    - Kalisz U18
    - Nagymaros U18
    - Czech U18 B

U14:
  name: U14
  teams:
    - KCNW U14
    - Powiśle U14
    - Glauchau U14
    - Leśna U14
    - Neuburg U14
    - Praha U14
    - SG Franken U14
    #- Praha U14 W
    - Ukraine U14

U12:
  name: U12
  teams:
    - KCNW U12
    - DFF Veltrusy U12
    - Praha U12
    - Nagymaros U12
    - Leśna U12
