MenElite:
  name: Men Elite
  teams:
    - VK Berlin
    - RKV Berlin
    - KSV Glauchau
    - DRC Neuburg
    - Set Kaniow A
    - Kaniow BKT
    - KV Nurnberg
    - Team Poznań
    - KC Kelheim
    - KP Bremen
    - WCH Berlin
    - KCNW U21
    #- Katowice M
    - Alytus
    - POL U21
    - KP Praha A

Ladies:
  name: Ladies
  teams:
    - Kaniow W
    - KCNW Berlin W
    - KSVH W
    - Neuburg W
    - Czech W
    - Czech/German
    - Bremen W
    - Katowice W
    - Powisle W

Men2:
  name: Men 2
  teams:
    - VMW Berlin Men
#    - Vidra Old Boys
    - Potsdam Men
    - Nagymaros Men
    - UKK Wien mix
    - Ukraine Men
    - Lesna Men
    - DobroPtaah

U18:
  name: U18
  teams:
    - Alytus U18
    - Czech U18 A
    - KCNW U16
    - Lesna U18
    - Kalisz U18
    - Nagymaros U18
    - Czech U18 B

U14:
  name: U14
  teams:
    - KCNW U14
    - Powisle U14
    - Glauchau U14
    - Lesna U14
    - Neuburg U14
    - Praha U14
    - SG Franken U14
    #- Praha U14 W
    - Ukraine U14

U12:
  name: U12
  teams:
    - KCNW U12
    - DFF Veltrusy U12
    - Praha U12
    - Nagymarosz U12
    - Lesna U12
